### ISSUE TITLE
Gather node does not maintain custom audio choice

### ISSUE THREAD

**Issue by Megamuch** [jambonz/node-red-contrib-jambonz#34]
There is small bug in the gather node under the prompt settings. 
If the prompt settings are changed lets say google, dutch, wavenet-d) on next open it will keep the vendor (google) and language (dutch) choice but the voice always defaults to standard-a-female.

The Say node is unaffected.

**Comment by avoylenko** [comment]
Should be fixed in 2.4.1

**Comment by sammachin** [comment]
Confirmed fixed in 2.4.4, @davehorton please close this issue
