### ISSUE TITLE
Dial for teams returning incorrect parameter

### ISSUE THREAD

**Issue by jontyk** [jambonz/node-red-contrib-jambonz#4]
jambonz feature server is expecting
`{"dial":{"target":[{"type":"teams","number":"{+E164}"}],"answerOnBridge":false,"callerId":"{+E164}"}}`
nodered app is returning
`{"dial":{"target":[{"type":"teams","user":"{+E164}"}],"answerOnBridge":false,"callerId":"{+E164}"}}`

https://github.com/jambonz/node-red-contrib-jambonz/blob/4dc73bc2924c7d3ff4f7cf62d4527366f316eeae/src/nodes/jambonz.js#L545

**Comment by davehorton** [comment]
fixed
