### ISSUE TITLE
Bargein property not available in verb Gather 

### ISSUE THREAD

**Issue by intellipawan** [jambonz/node-red-contrib-jambonz#45]
Bargein property of Gather which is listed in document on jambonz.org  (https://www.jambonz.org/docs/webhooks/gather/)  but it is not available in Node-Red contribution. How do I use "bargein" in this Node-Red contribution?

**Comment by avoylenko** [comment]
@intellipawan solved, please upgrade to 2.4.9 version

**Comment by avoylenko** [comment]
@davehorton could you close this?
